# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: foo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: foo

      ME_CONFIG_MONGODB_URL: mongodb://root:foo@mongo:27017/

      ME_CONFIG_BASICAUTH_USERNAME: foo
      ME_CONFIG_BASICAUTH_PASSWORD: bar
